[package]
name = "user"
version = "0.1.0"
edition = "2021"
authors = ["Chris Berner <christopherberner@gmail.com>"]
license = "CC0-1.0"
description = "A Rust project"
repository = "https://github.com/cberner-devin/user"

[dependencies]
